package co.gov.ideam.sirh.ws;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)

@WebServiceClient(wsdlLocation="http://sirh.ideam.gov.co:8230/Ideam-Ejb/ExportSirh/ExportaDatosSirh?wsdl",
  targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/", name="ExportSirh")
public class ExportSirh
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static {
    try
    {
      logger = Logger.getLogger("co.gov.ideam.sirh.ws.ExportSirh");
      URL baseUrl = ExportSirh.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            ExportSirh.class.getResource("http://sirh.ideam.gov.co:8230/Ideam-Ejb/ExportSirh/ExportaDatosSirh?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://sirh.ideam.gov.co:8230/Ideam-Ejb/ExportSirh/ExportaDatosSirh?wsdl");
        }
      }
      else
      {
        wsdlLocationURL =
            new URL(baseUrl, "http://sirh.ideam.gov.co:8230/Ideam-Ejb/ExportSirh/ExportaDatosSirh?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://sirh.ideam.gov.co:8230/Ideam-Ejb/ExportSirh/ExportaDatosSirh?wsdl",
          e);
    }
  }

  public ExportSirh()
  {
    super(wsdlLocationURL,
          new QName("http://businessl.webservices.sirh.ideam.gov.co/",
                    "ExportSirh"));
  }

  public ExportSirh(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="ExportaDatosSirhPort")
  public ExportaDatosSirh getExportaDatosSirhPort()
  {
    return (ExportaDatosSirh) super.getPort(new QName("http://businessl.webservices.sirh.ideam.gov.co/",
                                                      "ExportaDatosSirhPort"),
                                            ExportaDatosSirh.class);
  }

  @WebEndpoint(name="ExportaDatosSirhPort")
  public ExportaDatosSirh getExportaDatosSirhPort(WebServiceFeature[] features)
  {
    return (ExportaDatosSirh) super.getPort(new QName("http://businessl.webservices.sirh.ideam.gov.co/",
                                                      "ExportaDatosSirhPort"),
                                            ExportaDatosSirh.class,
                                            features);
  }
}
