package co.gov.ideam.sirh.ws;

import co.gov.ideam.sirh.ws.ExportSirh;
import co.gov.ideam.sirh.ws.ExportaDatosSirh;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)

public class ExportaDatosSirhPortClient
{
  @WebServiceRef
  private static ExportSirh exportSirh;

  public static void main(String [] args)
  {
    exportSirh = new ExportSirh();
    ExportaDatosSirh exportaDatosSirh = exportSirh.getExportaDatosSirhPort();
    // Add your code to call the desired methods.
  }
}
