package co.gov.ideam.sirh.ws;

import co.gov.ideam.sirh.ws.model.DataWebService;
import co.gov.ideam.sirh.ws.model.ObjectFactory;
import co.gov.ideam.sirh.ws.model.SingleRowWebService;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)

@WebService(wsdlLocation="http://sirh.ideam.gov.co:8230/Ideam-Ejb/ExportSirh/ExportaDatosSirh?wsdl",
  targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/", name="ExportaDatosSirh")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface ExportaDatosSirh
{
  @WebMethod
  @Action(input="http://businessl.webservices.sirh.ideam.gov.co/ExportaDatosSirh/getSingleData", fault =
      { @FaultAction(value="http://businessl.webservices.sirh.ideam.gov.co/ExportaDatosSirh/getSingleData/Fault/IdeamException",
          className = IdeamException.class)
        } , output="http://businessl.webservices.sirh.ideam.gov.co/ExportaDatosSirh/getSingleDataResponse")
  @ResponseWrapper(localName="getSingleDataResponse", targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/",
    className="co.gov.ideam.sirh.ws.model.GetSingleDataResponse")
  @RequestWrapper(localName="getSingleData", targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/",
    className="co.gov.ideam.sirh.ws.model.GetSingleData")
  @WebResult(targetNamespace="", name="singleData")
  public DataWebService getSingleData(@WebParam(targetNamespace="", name="arg0")
    Long arg0, @WebParam(targetNamespace="", name="arg1")
    List<Object> arg1)
    throws IdeamException;

  @WebMethod
  @Action(input="http://businessl.webservices.sirh.ideam.gov.co/ExportaDatosSirh/getOneRow", fault =
      { @FaultAction(value="http://businessl.webservices.sirh.ideam.gov.co/ExportaDatosSirh/getOneRow/Fault/IdeamException",
          className = IdeamException.class)
        } , output="http://businessl.webservices.sirh.ideam.gov.co/ExportaDatosSirh/getOneRowResponse")
  @ResponseWrapper(localName="getOneRowResponse", targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/",
    className="co.gov.ideam.sirh.ws.model.GetOneRowResponse")
  @RequestWrapper(localName="getOneRow", targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/",
    className="co.gov.ideam.sirh.ws.model.GetOneRow")
  @WebResult(targetNamespace="", name="singleRow")
  public SingleRowWebService getOneRow(@WebParam(targetNamespace="", name="arg0")
    Long arg0, @WebParam(targetNamespace="", name="arg1")
    List<Object> arg1)
    throws IdeamException;

  @WebMethod
  @Action(input="http://businessl.webservices.sirh.ideam.gov.co/ExportaDatosSirh/getMultipleRows", fault =
      { @FaultAction(value="http://businessl.webservices.sirh.ideam.gov.co/ExportaDatosSirh/getMultipleRows/Fault/IdeamException",
          className = IdeamException.class)
        } , output="http://businessl.webservices.sirh.ideam.gov.co/ExportaDatosSirh/getMultipleRowsResponse")
  @ResponseWrapper(localName="getMultipleRowsResponse", targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/",
    className="co.gov.ideam.sirh.ws.model.GetMultipleRowsResponse")
  @RequestWrapper(localName="getMultipleRows", targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/",
    className="co.gov.ideam.sirh.ws.model.GetMultipleRows")
  @WebResult(targetNamespace="", name="multipleRows")
  public List<SingleRowWebService> getMultipleRows(@WebParam(targetNamespace="",
      name="arg0")
    Long arg0, @WebParam(targetNamespace="", name="arg1")
    List<Object> arg1)
    throws IdeamException;
}
