package co.gov.ideam.sirh.ws;

import javax.xml.ws.WebFault;

@WebFault(faultBean="co.gov.ideam.sirh.ws.model.IdeamException",
  targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/", name="IdeamException")
public class IdeamException
  extends Exception
{
  private co.gov.ideam.sirh.ws.model.IdeamException faultInfo;

  public IdeamException(String message,
                        co.gov.ideam.sirh.ws.model.IdeamException faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public IdeamException(String message,
                        co.gov.ideam.sirh.ws.model.IdeamException faultInfo,
                        Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public co.gov.ideam.sirh.ws.model.IdeamException getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(co.gov.ideam.sirh.ws.model.IdeamException faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)
