package co.gov.ideam.sirh.dataimport.client;

import javax.xml.ws.WebFault;

@WebFault(faultBean="co.gov.ideam.sirh.dataimport.client.generate.Exception",
  targetNamespace="http://servicio.sirh.ideam.gov.co/", name="Exception")
public class Exception
  extends java.lang.Exception
{
  private co.gov.ideam.sirh.dataimport.client.generate.Exception faultInfo;

  public Exception(String message,
                   co.gov.ideam.sirh.dataimport.client.generate.Exception faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public Exception(String message,
                   co.gov.ideam.sirh.dataimport.client.generate.Exception faultInfo,
                   Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public co.gov.ideam.sirh.dataimport.client.generate.Exception getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(co.gov.ideam.sirh.dataimport.client.generate.Exception faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)
