package co.gov.ideam.sirh.dataimport.client;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)

@WebServiceClient(wsdlLocation="http://localhost:18081/WebServiceCAR/ImportDatosSirh/DataSirh?wsdl",
  targetNamespace="http://servicio.sirh.ideam.gov.co/", name="ImportDatosSirh")
public class ImportDatosSirh
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static {
    try
    {
      logger = Logger.getLogger("co.gov.ideam.sirh.dataimport.client.ImportDatosSirh");
      URL baseUrl = ImportDatosSirh.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            ImportDatosSirh.class.getResource("http://localhost:18081/WebServiceCAR/ImportDatosSirh/DataSirh?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://localhost:18081/WebServiceCAR/ImportDatosSirh/DataSirh?wsdl");
        }
      }
      else
      {
        wsdlLocationURL =
            new URL(baseUrl, "http://localhost:18081/WebServiceCAR/ImportDatosSirh/DataSirh?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://localhost:18081/WebServiceCAR/ImportDatosSirh/DataSirh?wsdl",
          e);
    }
  }

  public ImportDatosSirh()
  {
    super(wsdlLocationURL,
          new QName("http://servicio.sirh.ideam.gov.co/", "ImportDatosSirh"));
  }

  public ImportDatosSirh(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="DataSirhPort")
    public DataSirh getDataSirhPort(String nameSpace)
    {   
       return (DataSirh) super.getPort(new QName(nameSpace,
                                                "DataSirhPort"),
                                      DataSirh.class);
  }

  @WebEndpoint(name="DataSirhPort")
  public DataSirh getDataSirhPort(WebServiceFeature[] features)
  {
    return (DataSirh) super.getPort(new QName("http://servicio.sirh.ideam.gov.co/",
                                              "DataSirhPort"),
                                    DataSirh.class, features);
  }
}
