package co.gov.ideam.sirh.remoto.sender.modelo;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)

@WebServiceClient(wsdlLocation="receiver.wsdl", targetNamespace="http://sirh.ideam.gov.co/",
  name="Receiver")
public class Receiver
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static {
    try
    {
      logger = Logger.getLogger("co.gov.ideam.sirh.remoto.sender.modelo.Receiver");
      URL baseUrl = Receiver.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL = Receiver.class.getResource("receiver.wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL = new URL(baseUrl, "receiver.wsdl");
        }
      }
      else
      {
        wsdlLocationURL = new URL(baseUrl, "receiver.wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using receiver.wsdl", e);
    }
  }

  public Receiver()
  {
    super(wsdlLocationURL,
          new QName("http://sirh.ideam.gov.co/", "Receiver"));
  }

  public Receiver(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="RegistroRemotoSirhPort")
  public RegistroRemotoSirh getRegistroRemotoSirhPort()
  {
    return (RegistroRemotoSirh) super.getPort(new QName("http://sirh.ideam.gov.co/",
                                                        "RegistroRemotoSirhPort"),
                                              RegistroRemotoSirh.class);
  }

  @WebEndpoint(name="RegistroRemotoSirhPort")
  public RegistroRemotoSirh getRegistroRemotoSirhPort(WebServiceFeature[] features)
  {
    return (RegistroRemotoSirh) super.getPort(new QName("http://sirh.ideam.gov.co/",
                                                        "RegistroRemotoSirhPort"),
                                              RegistroRemotoSirh.class,
                                              features);
  }
}
