package co.gov.ideam.sirh.webservices.businessl;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)

@WebService(wsdlLocation="http://127.0.0.1:7101/Ideam-Ejb/ExportSirh/ExportaDatosSirh?wsdl?wsdl",
  targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/", name="ExportaDatosSirh")
@XmlSeeAlso(
  { co.gov.ideam.sirh.webservices.businessl.ObjectFactory.class, co.gov.ideam.sirh.webservices.businessl.types.ObjectFactory.class, net.java.dev.jaxb.array.ObjectFactory.class })
public interface ExportaDatosSirh
{
  @WebMethod
  @Action(input="", fault =
      { @FaultAction(value="http://businessl.webservices.sirh.ideam.gov.co/ExportaDatosSirh/getSingleData/Fault/IdeamException",
          className=co.gov.ideam.sirh.webservices.businessl.IdeamException.class)
        } , output="")
  @ResponseWrapper(localName="getSingleDataResponse", targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/",
    className="co.gov.ideam.sirh.webservices.businessl.GetSingleDataResponse")
  @RequestWrapper(localName="getSingleData", targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/",
    className="co.gov.ideam.sirh.webservices.businessl.GetSingleData")
  @WebResult(targetNamespace="", name="singleData")
  public co.gov.ideam.sirh.webservices.businessl.types.DataWebService getSingleData(@WebParam(targetNamespace="",
      name="arg0")
    long arg0, @WebParam(targetNamespace="", name="arg1")
    List<Object> arg1)
    throws co.gov.ideam.sirh.webservices.businessl.IdeamException_Exception;

  @WebMethod
  @Action(input="", fault =
      { @FaultAction(value="http://businessl.webservices.sirh.ideam.gov.co/ExportaDatosSirh/getOneRow/Fault/IdeamException",
          className=co.gov.ideam.sirh.webservices.businessl.IdeamException.class)
        } , output="")
  @ResponseWrapper(localName="getOneRowResponse", targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/",
    className="co.gov.ideam.sirh.webservices.businessl.GetOneRowResponse")
  @RequestWrapper(localName="getOneRow", targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/",
    className="co.gov.ideam.sirh.webservices.businessl.GetOneRow")
  @WebResult(targetNamespace="", name="singleRow")
  public co.gov.ideam.sirh.webservices.businessl.types.SingleRowWebService getOneRow(@WebParam(targetNamespace="",
      name="arg0")
    long arg0, @WebParam(targetNamespace="", name="arg1")
    List<Object> arg1)
    throws co.gov.ideam.sirh.webservices.businessl.IdeamException_Exception;

  @WebMethod
  @Action(input="", fault =
      { @FaultAction(value="http://businessl.webservices.sirh.ideam.gov.co/ExportaDatosSirh/getMultipleRows/Fault/IdeamException",
          className=co.gov.ideam.sirh.webservices.businessl.IdeamException.class)
        } , output="")
  @ResponseWrapper(localName="getMultipleRowsResponse", targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/",
    className="co.gov.ideam.sirh.webservices.businessl.GetMultipleRowsResponse")
  @RequestWrapper(localName="getMultipleRows", targetNamespace="http://businessl.webservices.sirh.ideam.gov.co/",
    className="co.gov.ideam.sirh.webservices.businessl.GetMultipleRows")
  @WebResult(targetNamespace="", name="multipleRows")
  public List<co.gov.ideam.sirh.webservices.businessl.types.SingleRowWebService> getMultipleRows(@WebParam(targetNamespace="",
      name="arg0")
    long arg0, @WebParam(targetNamespace="", name="arg1")
    List<Object> arg1)
    throws co.gov.ideam.sirh.webservices.businessl.IdeamException_Exception;
}
