package co.gov.ideam.sirh.webservices.businessl;

import co.gov.ideam.sirh.webservices.businessl.ExportSirh;
import co.gov.ideam.sirh.webservices.businessl.ExportaDatosSirh;

import co.gov.ideam.sirh.webservices.businessl.types.DataWebService;
import co.gov.ideam.sirh.webservices.businessl.types.SingleRowWebService;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)

public class ExportaDatosSirhPortClient {


    public static void main(String[] args) {
        


    }
}
