package co.gov.corpocaldas.cliente;

import co.gov.corpocaldas.cliente.DataSirh;
import co.gov.corpocaldas.cliente.DataSirhSoap;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)

public class DataSirhSoap12Client
{
  @WebServiceRef
  private static DataSirh dataSirh;

  public static void main(String [] args)
  {
    dataSirh = new DataSirh();
    DataSirhSoap dataSirhSoap = dataSirh.getDataSirhSoap12();
    // Add your code to call the desired methods.
  }
}
