package co.gov.corpocaldas.cliente;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)

@WebService(wsdlLocation="DataSirh.wsdl", targetNamespace="WebServiceCAR",
  name="DataSirhSoap")
@XmlSeeAlso(
  { co.gov.corpocaldas.generated.ObjectFactory.class })
public interface DataSirhSoap
{
  @WebMethod(action="WebServiceCAR/getAllFuentes")
  @Action(input="WebServiceCAR/getAllFuentes", output="WebServiceCAR/DataSirhSoap/getAllFuentesResponse")
  @ResponseWrapper(localName="getAllFuentesResponse", targetNamespace="WebServiceCAR",
    className="co.gov.corpocaldas.generated.GetAllFuentesResponse")
  @RequestWrapper(localName="getAllFuentes", targetNamespace="WebServiceCAR",
    className="co.gov.corpocaldas.generated.GetAllFuentes")
  @WebResult(targetNamespace="WebServiceCAR", name="getAllFuentesResult")
  public co.gov.corpocaldas.generated.ArrayOfFntvFuentesTramos getAllFuentes();

  @WebMethod(action="WebServiceCAR/getAllUsuariosNaturalConcesion")
  @Action(input="WebServiceCAR/getAllUsuariosNaturalConcesion", output="WebServiceCAR/DataSirhSoap/getAllUsuariosNaturalConcesionResponse")
  @ResponseWrapper(localName="getAllUsuariosNaturalConcesionResponse",
    targetNamespace="WebServiceCAR", className="co.gov.corpocaldas.generated.GetAllUsuariosNaturalConcesionResponse")
  @RequestWrapper(localName="getAllUsuariosNaturalConcesion",
    targetNamespace="WebServiceCAR", className="co.gov.corpocaldas.generated.GetAllUsuariosNaturalConcesion")
  @WebResult(targetNamespace="WebServiceCAR", name="getAllUsuariosNaturalConcesionResult")
  public co.gov.corpocaldas.generated.ArrayOfRegUserNaturalConcesion getAllUsuariosNaturalConcesion();
}
