package co.gov.corpocaldas.cliente;

import co.gov.corpocaldas.cliente.DataSirh;
import co.gov.corpocaldas.cliente.DataSirhSoap;

import co.gov.corpocaldas.generated.ArrayOfFntvFuentesTramos;

import co.gov.corpocaldas.generated.FntvFuentesTramos;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)

public class DataSirhSoapClient
{
  @WebServiceRef
  private static DataSirh dataSirh;

  public static void main(String [] args)
  {
    dataSirh = new DataSirh();
    DataSirhSoap dataSirhSoap = dataSirh.getDataSirhSoap();
    // Add your code to call the desired methods.
    System.out.println("Obj_webServiceSoap MAIN: "+dataSirhSoap);
    // FUENTES
     ArrayOfFntvFuentesTramos result = new ArrayOfFntvFuentesTramos();
     System.out.println("Resultado MAIN: "+result);
     result= dataSirhSoap.getAllFuentes();

     System.out.println("Numero Fuentes MAIN: "+result.getFntvFuentesTramos().size());

          if(result.getFntvFuentesTramos()!=null){
             int it =1;
             for(FntvFuentesTramos ft:result.getFntvFuentesTramos())  {            
                System.out.println("Fuente: "+it+" id Fuente: "+ft.getIdfuente()+" Fuente: "+ft.getNombrefuente()+" Area: "+ft.getArea());
                it++;
              }
         }   
  }
}
