package co.gov.ideam.sirh.webservices.receptor;

import co.gov.ideam.sirh.webservices.receptor.Receiver;
import co.gov.ideam.sirh.webservices.receptor.RegistroRemotoSirh;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)

public class RegistroRemotoSirhPortClient
{
  @WebServiceRef
  private static Receiver receiver;

  public static void main(String [] args)
  {
    receiver = new Receiver();
    RegistroRemotoSirh registroRemotoSirh = receiver.getRegistroRemotoSirhPort();
    // Add your code to call the desired methods.
  }
}
