package co.gov.ideam.sirh.webservices.receptor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)

@WebService(wsdlLocation="http://127.0.0.1:7101/Ideam-Ejb/Receiver/RegistroRemotoSirh?wsdl?wsdl",
  targetNamespace="http://sirh.ideam.gov.co/", name="RegistroRemotoSirh")
@XmlSeeAlso(
  { co.gov.ideam.sirh.webservices.receptor.types.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface RegistroRemotoSirh
{
  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="", fault =
      { @FaultAction(value="http://sirh.ideam.gov.co/RegistroRemotoSirh/recibirEvento/Fault/IdeamException",
          className=co.gov.ideam.sirh.webservices.receptor.IdeamException.class)
        } , output="")
  @WebResult(targetNamespace="http://sirh.ideam.gov.co/", partName="parameters",
    name="recibirEventoResponse")
  public co.gov.ideam.sirh.webservices.receptor.types.RecibirEventoResponse recibirEvento(@WebParam(targetNamespace="http://sirh.ideam.gov.co/",
      partName="parameters", name="recibirEvento")
    co.gov.ideam.sirh.webservices.receptor.types.RecibirEvento parameters)
    throws co.gov.ideam.sirh.webservices.receptor.IdeamException;
}
